In [1]:
# 导入相关数据包
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('data/000000_0', sep='|', 
                   names = ["device_id", "vc_id", "vd_id", "index_name", "index_tag", "index_value", "time", "date"])
data.head()

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
0,2400,22,vm-100,cpu.usage.average,\N,270.0,2018-10-31 00:00:20,2018-10-31
1,2400,22,vm-100,mem.usage.average,\N,599.0,2018-10-31 00:00:20,2018-10-31
2,2400,22,vm-100,datastore.maxTotalLatency.latest,\N,0.0,2018-10-31 00:00:20,2018-10-31
3,2400,22,vm-100,net.bytesRx.average,\N,0.0,2018-10-31 00:00:20,2018-10-31
4,2400,22,vm-100,net.bytesTx.average,\N,0.0,2018-10-31 00:00:20,2018-10-31

In [3]:
for i in range(1, 8):
    file_path = 'data/00000{}_0'.format(i)
    d = pd.read_csv(file_path, sep='|', 
                   names = ["device_id", "vc_id", "vd_id", "index_name", "index_tag", "index_value", "time", "date"])
    data = data.append(d)

In [4]:
data.groupby(['index_name', 'index_tag'])['index_value'].sum()

index_name                               index_tag
cpu.usage.average                        \N           8.556951e+07
datastore.maxTotalLatency.latest         \N          -1.530000e+02
mem.usage.average                        \N           2.260542e+08
net.bytesRx.average                      \N           5.440487e+07
net.bytesTx.average                      \N           7.533441e+07
net.droppedRx.summation                  \N           2.562000e+03
net.droppedTx.summation                  \N          -2.100000e+02
net.packetsRx.summation                  \N           1.631089e+09
net.packetsTx.summation                  \N           1.415319e+09
net.usage.average                        4000         1.298638e+08
                                         4001         1.970000e+02
                                         \N           1.298665e+08
                                         vmnic0      -2.120000e+02
                                         vmnic1      -2.120000e+02
                                         vmnic2       3.540017e+07
                                         vmnic3       9.297545e+07
                                         vmnic4      -2.120000e+02
                                         vmnic5      -2.120000e+02
virtualDisk.numberReadAveraged.average   scsi0:0      1.539470e+05
                                         scsi0:1      2.185500e+04
virtualDisk.numberWriteAveraged.average  scsi0:0      1.045500e+05
                                         scsi0:1     -1.150000e+02
virtualDisk.read.average                 \N           2.413653e+06
virtualDisk.write.average                \N           1.230072e+07
Name: index_value, dtype: float64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9299728 entries, 0 to 360942
Data columns (total 8 columns):
device_id      int64
vc_id          int64
vd_id          object
index_name     object
index_tag      object
index_value    float64
time           object
date           object
dtypes: float64(1), int64(2), object(5)
memory usage: 638.6+ MB

In [6]:
data.tail()

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
360938,7361,22,vm-914,net.usage.average,4001,0.0,2018-11-15 23:59:00,2018-11-15
360939,7361,22,vm-914,net.usage.average,4000,2.0,2018-11-15 23:59:00,2018-11-15
360940,7361,22,vm-914,net.usage.average,vmnic5,0.0,2018-11-15 23:59:00,2018-11-15
360941,7361,22,vm-914,net.usage.average,vmnic2,0.0,2018-11-15 23:59:00,2018-11-15
360942,7361,22,vm-914,net.usage.average,vmnic3,1.0,2018-11-15 23:59:00,2018-11-15

In [7]:
data.describe()

          device_id      vc_id   index_value
count  9.299728e+06  9299728.0  9.299728e+06
mean   5.687065e+03       22.0  4.183857e+02
std    2.346394e+03        0.0  7.794878e+03
min    2.400000e+03       22.0 -1.000000e+00
25%    2.400000e+03       22.0  0.000000e+00
50%    7.361000e+03       22.0  0.000000e+00
75%    7.363000e+03       22.0  6.000000e+00
max    7.363000e+03       22.0  1.181681e+06

In [8]:
data['device_id'].value_counts()

2400    3139124
7361    3133678
7363    3026926
Name: device_id, dtype: int64

In [9]:
data['vc_id'].value_counts()

22    9299728
Name: vc_id, dtype: int64

In [10]:
data['vd_id'].value_counts()

vm-100    3139124
vm-914    3133678
vm-913    3026926
Name: vd_id, dtype: int64

In [11]:
data.groupby(['device_id', 'vd_id'])['device_id'].count()

device_id  vd_id
2400       vm-100    3139124
7361       vm-914    3133678
7363       vm-913    3026926
Name: device_id, dtype: int64

In [12]:
data['index_name'].value_counts()

net.usage.average                          4144422
mem.usage.average                           509680
datastore.maxTotalLatency.latest            509680
net.packetsTx.summation                     509676
net.droppedTx.summation                     509675
net.droppedRx.summation                     509675
net.bytesTx.average                         509675
net.bytesRx.average                         509675
net.packetsRx.summation                     509675
cpu.usage.average                           509675
virtualDisk.numberReadAveraged.average      162161
virtualDisk.numberWriteAveraged.average     162161
virtualDisk.read.average                    121949
virtualDisk.write.average                   121949
Name: index_name, dtype: int64

In [13]:
data.groupby(['device_id', 'index_name'])['index_value'].mean()

device_id  index_name
2400       cpu.usage.average                           462.617214
           datastore.maxTotalLatency.latest             -0.000704
           mem.usage.average                          1118.608089
           net.bytesRx.average                           1.351822
           net.bytesTx.average                           0.740639
           net.droppedRx.summation                      -0.000974
           net.droppedTx.summation                      -0.001044
           net.packetsRx.summation                     170.962513
           net.packetsTx.summation                      58.253253
           net.usage.average                             0.677296
           virtualDisk.numberReadAveraged.average        2.143340
           virtualDisk.numberWriteAveraged.average       0.380906
           virtualDisk.read.average                     37.510942
           virtualDisk.write.average                    17.097657
7361       cpu.usage.average                            16.489367
           datastore.maxTotalLatency.latest             -0.000111
           mem.usage.average                           103.220969
           net.bytesRx.average                          51.950465
           net.bytesTx.average                         122.847374
           net.droppedRx.summation                      -0.000012
           net.droppedTx.summation                      -0.000100
           net.packetsRx.summation                    4992.858551
           net.packetsTx.summation                    4409.490140
           net.usage.average                            62.575065
           virtualDisk.numberReadAveraged.average        0.007131
           virtualDisk.numberWriteAveraged.average       0.390953
           virtualDisk.read.average                      3.565575
           virtualDisk.write.average                     6.858557
7363       cpu.usage.average                            23.126722
           datastore.maxTotalLatency.latest             -0.000083
           mem.usage.average                           105.356028
           net.bytesRx.average                         268.974849
           net.bytesTx.average                         321.967517
           net.droppedRx.summation                       0.016209
           net.droppedTx.summation                      -0.000089
           net.packetsRx.summation                    4448.395965
           net.packetsTx.summation                    3872.917132
           net.usage.average                           220.790175
           virtualDisk.numberReadAveraged.average        0.076596
           virtualDisk.numberWriteAveraged.average       1.413350
           virtualDisk.read.average                     18.562853
           virtualDisk.write.average                   276.901561
Name: index_value, dtype: float64

In [14]:
data.groupby(['device_id', 'index_tag'])['device_id'].count()

device_id  index_tag
2400       4000          170462
           \N           1785038
           scsi0:0        80424
           scsi0:1        80424
           vmnic0        170463
           vmnic1        170463
           vmnic2        170463
           vmnic3        170462
           vmnic4        170462
           vmnic5        170463
7361       4000          170790
           4001           67010
           \N           1789522
           scsi0:0        81616
           vmnic0        170790
           vmnic1        170790
           vmnic2        170790
           vmnic3        170790
           vmnic4        170790
           vmnic5        170790
7363       4000          168424
           \N           1766100
           scsi0:0        81858
           vmnic0        168424
           vmnic1        168424
           vmnic2        168424
           vmnic3        168424
           vmnic4        168424
           vmnic5        168424
Name: device_id, dtype: int64

In [15]:
device01 = data.loc[data['device_id'] == 2400]
device01.head()

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
0,2400,22,vm-100,cpu.usage.average,\N,270.0,2018-10-31 00:00:20,2018-10-31
1,2400,22,vm-100,mem.usage.average,\N,599.0,2018-10-31 00:00:20,2018-10-31
2,2400,22,vm-100,datastore.maxTotalLatency.latest,\N,0.0,2018-10-31 00:00:20,2018-10-31
3,2400,22,vm-100,net.bytesRx.average,\N,0.0,2018-10-31 00:00:20,2018-10-31
4,2400,22,vm-100,net.bytesTx.average,\N,0.0,2018-10-31 00:00:20,2018-10-31

In [16]:
device01.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3139124 entries, 0 to 360920
Data columns (total 8 columns):
device_id      int64
vc_id          int64
vd_id          object
index_name     object
index_tag      object
index_value    float64
time           object
date           object
dtypes: float64(1), int64(2), object(5)
memory usage: 215.5+ MB

In [17]:
device01['date'].value_counts()

2018-11-04    66102
2018-11-06    66079
2018-11-05    66079
2018-11-08    66033
2018-11-11    65943
2018-11-03    65803
2018-11-13    65412
2018-11-02    65389
2018-11-10    65205
2018-11-09    65159
2018-11-12    65021
2018-11-15    63779
2018-11-07    63595
2018-11-01    52106
2018-11-14    51244
2018-09-18    48977
2018-09-21    48960
2018-09-22    48960
2018-10-06    48960
2018-10-09    48960
2018-09-16    48960
2018-10-28    48960
2018-10-08    48960
2018-09-24    48960
2018-10-25    48960
2018-10-02    48960
2018-10-14    48960
2018-09-19    48960
2018-09-28    48960
2018-10-31    48960
              ...
2018-10-04    48960
2018-10-24    48960
2018-10-05    48960
2018-10-20    48960
2018-10-26    48960
2018-09-20    48960
2018-09-17    48943
2018-10-07    48943
2018-10-10    48943
2018-09-30    48943
2018-10-18    48943
2018-09-25    48926
2018-09-26    48926
2018-10-03    48926
2018-10-19    48926
2018-10-17    48926
2018-09-29    48926
2018-09-23    48926
2018-10-30    48909
2018-10-16    48909
2018-10-29    48909
2018-10-23    48892
2018-10-15    48782
2018-10-11    48331
2018-10-13    47940
2018-10-12    46767
2018-09-27    46053
2018-10-22    46002
2018-10-21    24752
2018-10-27    17595
Name: date, Length: 61, dtype: int64

In [18]:
device01['time'].value_counts()

2018-10-03 19:54:20    68
2018-11-14 20:49:20    46
2018-11-06 02:05:20    46
2018-11-12 04:51:20    46
2018-11-14 20:51:20    46
2018-11-06 02:07:20    46
2018-10-16 00:37:20    34
2018-09-23 04:49:40    34
2018-10-16 00:36:20    34
2018-10-04 06:10:20    34
2018-10-16 00:45:20    34
2018-11-08 11:05:20    23
2018-11-01 18:05:00    23
2018-11-14 19:48:20    23
2018-11-08 10:22:40    23
2018-11-09 17:55:40    23
2018-11-09 09:19:40    23
2018-11-08 19:29:20    23
2018-11-10 18:28:20    23
2018-11-04 02:10:20    23
2018-11-15 00:10:20    23
2018-11-05 11:41:00    23
2018-11-06 09:03:40    23
2018-11-11 23:19:20    23
2018-11-05 00:36:20    23
2018-11-08 18:17:20    23
2018-11-12 13:42:20    23
2018-11-11 10:52:20    23
2018-11-09 01:24:20    23
2018-11-09 05:35:40    23
                       ..
2018-10-10 10:25:20    17
2018-10-28 19:35:20    17
2018-10-28 14:08:00    17
2018-09-25 07:24:40    17
2018-10-15 03:41:20    17
2018-10-08 20:30:20    17
2018-10-30 05:38:20    17
2018-09-18 15:29:00    17
2018-10-08 07:54:20    17
2018-09-22 07:08:20    17
2018-10-06 00:37:00    17
2018-09-29 18:41:20    17
2018-10-13 06:41:20    17
2018-09-24 10:18:40    17
2018-10-06 11:47:20    17
2018-10-03 18:32:20    17
2018-09-29 00:17:00    17
2018-10-02 09:27:20    17
2018-10-08 00:33:20    17
2018-10-31 00:02:40    17
2018-10-15 20:58:40    17
2018-09-26 12:27:00    17
2018-09-29 12:28:00    17
2018-09-25 05:59:00    17
2018-10-15 22:11:40    17
2018-10-10 14:14:40    17
2018-10-11 01:51:40    17
2018-10-15 01:22:20     9
2018-11-01 15:05:20     4
2018-11-11 00:53:40     2
Name: time, Length: 170451, dtype: int64

In [19]:
device01.groupby(['time', 'index_name'])['index_value'].agg(['sum', 'count'])

                                                               sum  count
time                index_name
2018-09-16 00:00:00 cpu.usage.average                        141.0      1
                    datastore.maxTotalLatency.latest           0.0      1
                    mem.usage.average                         99.0      1
                    net.bytesRx.average                        0.0      1
                    net.bytesTx.average                        0.0      1
                    net.droppedRx.summation                    0.0      1
                    net.droppedTx.summation                    0.0      1
                    net.packetsRx.summation                  155.0      1
                    net.packetsTx.summation                   31.0      1
                    net.usage.average                          2.0      8
2018-09-16 00:00:20 cpu.usage.average                        145.0      1
                    datastore.maxTotalLatency.latest           0.0      1
                    mem.usage.average                        199.0      1
                    net.bytesRx.average                        1.0      1
                    net.bytesTx.average                        0.0      1
                    net.droppedRx.summation                    0.0      1
                    net.droppedTx.summation                    0.0      1
                    net.packetsRx.summation                  208.0      1
                    net.packetsTx.summation                   63.0      1
                    net.usage.average                          5.0      8
2018-09-16 00:01:00 cpu.usage.average                        147.0      1
                    datastore.maxTotalLatency.latest           0.0      1
                    mem.usage.average                        199.0      1
                    net.bytesRx.average                        0.0      1
                    net.bytesTx.average                        0.0      1
                    net.droppedRx.summation                    0.0      1
                    net.droppedTx.summation                    0.0      1
                    net.packetsRx.summation                  119.0      1
                    net.packetsTx.summation                   32.0      1
                    net.usage.average                          2.0      8
...                                                            ...    ...
2018-11-15 23:58:40 virtualDisk.read.average                   3.0      1
                    virtualDisk.write.average                  4.0      1
2018-11-15 23:59:20 cpu.usage.average                         92.0      1
                    datastore.maxTotalLatency.latest           0.0      1
                    mem.usage.average                        499.0      1
                    net.bytesRx.average                        0.0      1
                    net.bytesTx.average                        0.0      1
                    net.droppedRx.summation                    0.0      1
                    net.droppedTx.summation                    0.0      1
                    net.packetsRx.summation                   87.0      1
                    net.packetsTx.summation                   37.0      1
                    net.usage.average                          0.0      8
                    virtualDisk.numberReadAveraged.average     2.0      2
                    virtualDisk.numberWriteAveraged.average    1.0      2
                    virtualDisk.read.average                   6.0      1
                    virtualDisk.write.average                  7.0      1
2018-11-15 23:59:40 cpu.usage.average                         93.0      1
                    datastore.maxTotalLatency.latest           0.0      1
                    mem.usage.average                        499.0      1
                    net.bytesRx.average                        0.0      1
                    net.bytesTx.average                        0.0      1
                    net.droppedRx.summation                    0.0      1
                    net.droppedTx.summation                    0.0      1
                    net.packetsRx.summation                   76.0      1
                    net.packetsTx.summation                   29.0      1
                    net.usage.average                          0.0      8
                    virtualDisk.numberReadAveraged.average     1.0      2
                    virtualDisk.numberWriteAveraged.average    1.0      2
                    virtualDisk.read.average                   3.0      1
                    virtualDisk.write.average                  4.0      1

[1865313 rows x 2 columns]

In [20]:
# 选一个时刻的数据进行研究
device01_time01 = device01.loc[device01['time'] == '2018-11-15 23:59:40']
device01_time01

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
360722,2400,22,vm-100,cpu.usage.average,\N,93.0,2018-11-15 23:59:40,2018-11-15
360723,2400,22,vm-100,mem.usage.average,\N,499.0,2018-11-15 23:59:40,2018-11-15
360724,2400,22,vm-100,datastore.maxTotalLatency.latest,\N,0.0,2018-11-15 23:59:40,2018-11-15
360725,2400,22,vm-100,net.bytesRx.average,\N,0.0,2018-11-15 23:59:40,2018-11-15
360726,2400,22,vm-100,net.bytesTx.average,\N,0.0,2018-11-15 23:59:40,2018-11-15
360727,2400,22,vm-100,net.packetsRx.summation,\N,76.0,2018-11-15 23:59:40,2018-11-15
360728,2400,22,vm-100,net.droppedRx.summation,\N,0.0,2018-11-15 23:59:40,2018-11-15
360729,2400,22,vm-100,net.droppedTx.summation,\N,0.0,2018-11-15 23:59:40,2018-11-15
360730,2400,22,vm-100,net.packetsTx.summation,\N,29.0,2018-11-15 23:59:40,2018-11-15
360731,2400,22,vm-100,virtualDisk.read.average,\N,3.0,2018-11-15 23:59:40,2018-11-15
360732,2400,22,vm-100,virtualDisk.write.average,\N,4.0,2018-11-15 23:59:40,2018-11-15
360733,2400,22,vm-100,virtualDisk.numberReadAveraged.average,scsi0:1,0.0,2018-11-15 23:59:40,2018-11-15
360734,2400,22,vm-100,virtualDisk.numberReadAveraged.average,scsi0:0,1.0,2018-11-15 23:59:40,2018-11-15
360735,2400,22,vm-100,net.usage.average,\N,0.0,2018-11-15 23:59:40,2018-11-15
360736,2400,22,vm-100,net.usage.average,vmnic5,0.0,2018-11-15 23:59:40,2018-11-15
360737,2400,22,vm-100,virtualDisk.numberWriteAveraged.average,scsi0:1,0.0,2018-11-15 23:59:40,2018-11-15
360738,2400,22,vm-100,net.usage.average,vmnic4,0.0,2018-11-15 23:59:40,2018-11-15
360739,2400,22,vm-100,net.usage.average,vmnic0,0.0,2018-11-15 23:59:40,2018-11-15
360740,2400,22,vm-100,virtualDisk.numberWriteAveraged.average,scsi0:0,1.0,2018-11-15 23:59:40,2018-11-15
360741,2400,22,vm-100,net.usage.average,4000,0.0,2018-11-15 23:59:40,2018-11-15
360742,2400,22,vm-100,net.usage.average,vmnic1,0.0,2018-11-15 23:59:40,2018-11-15
360743,2400,22,vm-100,net.usage.average,vmnic2,0.0,2018-11-15 23:59:40,2018-11-15
360744,2400,22,vm-100,net.usage.average,vmnic3,0.0,2018-11-15 23:59:40,2018-11-15

In [21]:
# pd.get_dummies(device01_time01,columns=['index_name'], prefix='index')

In [22]:
device01_time01.groupby(['device_id', 'index_name', 'index_tag'])['index_value'].sum()

device_id  index_name                               index_tag
2400       cpu.usage.average                        \N            93.0
           datastore.maxTotalLatency.latest         \N             0.0
           mem.usage.average                        \N           499.0
           net.bytesRx.average                      \N             0.0
           net.bytesTx.average                      \N             0.0
           net.droppedRx.summation                  \N             0.0
           net.droppedTx.summation                  \N             0.0
           net.packetsRx.summation                  \N            76.0
           net.packetsTx.summation                  \N            29.0
           net.usage.average                        4000           0.0
                                                    \N             0.0
                                                    vmnic0         0.0
                                                    vmnic1         0.0
                                                    vmnic2         0.0
                                                    vmnic3         0.0
                                                    vmnic4         0.0
                                                    vmnic5         0.0
           virtualDisk.numberReadAveraged.average   scsi0:0        1.0
                                                    scsi0:1        0.0
           virtualDisk.numberWriteAveraged.average  scsi0:0        1.0
                                                    scsi0:1        0.0
           virtualDisk.read.average                 \N             3.0
           virtualDisk.write.average                \N             4.0
Name: index_value, dtype: float64

In [23]:
device01.head()

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
0,2400,22,vm-100,cpu.usage.average,\N,270.0,2018-10-31 00:00:20,2018-10-31
1,2400,22,vm-100,mem.usage.average,\N,599.0,2018-10-31 00:00:20,2018-10-31
2,2400,22,vm-100,datastore.maxTotalLatency.latest,\N,0.0,2018-10-31 00:00:20,2018-10-31
3,2400,22,vm-100,net.bytesRx.average,\N,0.0,2018-10-31 00:00:20,2018-10-31
4,2400,22,vm-100,net.bytesTx.average,\N,0.0,2018-10-31 00:00:20,2018-10-31

In [24]:
device01.head().T

,0,1,2,3,4
device_id,2400,2400,2400,2400,2400
vc_id,22,22,22,22,22
vd_id,vm-100,vm-100,vm-100,vm-100,vm-100
index_name,cpu.usage.average,mem.usage.average,datastore.maxTotalLatency.latest,net.bytesRx.average,net.bytesTx.average
index_tag,\N,\N,\N,\N,\N
index_value,270,599,0,0,0
time,2018-10-31 00:00:20,2018-10-31 00:00:20,2018-10-31 00:00:20,2018-10-31 00:00:20,2018-10-31 00:00:20
date,2018-10-31,2018-10-31,2018-10-31,2018-10-31,2018-10-31

In [25]:
device01.axes

[Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                  8,      9,
             ...
             360911, 360912, 360913, 360914, 360915, 360916, 360917, 360918,
             360919, 360920],
            dtype='int64', length=3139124),
 Index(['device_id', 'vc_id', 'vd_id', 'index_name', 'index_tag', 'index_value',
        'time', 'date'],
       dtype='object')]

In [26]:
device01.dtypes

device_id        int64
vc_id            int64
vd_id           object
index_name      object
index_tag       object
index_value    float64
time            object
date            object
dtype: object

In [27]:
device01.shape

(3139124, 8)

In [28]:
device01.size

25112992

In [29]:
device01_time02 = device01.loc[device01['time'] == '2018-10-31 00:01:40']
device01_time02

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
156,2400,22,vm-100,cpu.usage.average,\N,225.0,2018-10-31 00:01:40,2018-10-31
157,2400,22,vm-100,mem.usage.average,\N,599.0,2018-10-31 00:01:40,2018-10-31
158,2400,22,vm-100,datastore.maxTotalLatency.latest,\N,0.0,2018-10-31 00:01:40,2018-10-31
159,2400,22,vm-100,net.bytesRx.average,\N,0.0,2018-10-31 00:01:40,2018-10-31
160,2400,22,vm-100,net.bytesTx.average,\N,0.0,2018-10-31 00:01:40,2018-10-31
161,2400,22,vm-100,net.packetsRx.summation,\N,100.0,2018-10-31 00:01:40,2018-10-31
162,2400,22,vm-100,net.droppedRx.summation,\N,0.0,2018-10-31 00:01:40,2018-10-31
163,2400,22,vm-100,net.droppedTx.summation,\N,0.0,2018-10-31 00:01:40,2018-10-31
164,2400,22,vm-100,net.packetsTx.summation,\N,25.0,2018-10-31 00:01:40,2018-10-31
165,2400,22,vm-100,net.usage.average,\N,0.0,2018-10-31 00:01:40,2018-10-31
166,2400,22,vm-100,net.usage.average,vmnic5,0.0,2018-10-31 00:01:40,2018-10-31
167,2400,22,vm-100,net.usage.average,vmnic2,0.0,2018-10-31 00:01:40,2018-10-31
168,2400,22,vm-100,net.usage.average,vmnic1,0.0,2018-10-31 00:01:40,2018-10-31
169,2400,22,vm-100,net.usage.average,vmnic0,0.0,2018-10-31 00:01:40,2018-10-31
170,2400,22,vm-100,net.usage.average,vmnic4,0.0,2018-10-31 00:01:40,2018-10-31
171,2400,22,vm-100,net.usage.average,4000,0.0,2018-10-31 00:01:40,2018-10-31
172,2400,22,vm-100,net.usage.average,vmnic3,0.0,2018-10-31 00:01:40,2018-10-31

In [30]:
device01_time03 = device01.loc[device01['time'] == '2018-11-02 03:37:00']
device01_time03

,device_id,vc_id,vd_id,index_name,index_tag,index_value,time,date
329078,2400,22,vm-100,cpu.usage.average,\N,202.0,2018-11-02 03:37:00,2018-11-02
329079,2400,22,vm-100,mem.usage.average,\N,399.0,2018-11-02 03:37:00,2018-11-02
329080,2400,22,vm-100,datastore.maxTotalLatency.latest,\N,0.0,2018-11-02 03:37:00,2018-11-02
329081,2400,22,vm-100,net.bytesRx.average,\N,0.0,2018-11-02 03:37:00,2018-11-02
329082,2400,22,vm-100,net.bytesTx.average,\N,0.0,2018-11-02 03:37:00,2018-11-02
329083,2400,22,vm-100,net.packetsRx.summation,\N,48.0,2018-11-02 03:37:00,2018-11-02
329084,2400,22,vm-100,net.droppedRx.summation,\N,0.0,2018-11-02 03:37:00,2018-11-02
329085,2400,22,vm-100,net.droppedTx.summation,\N,0.0,2018-11-02 03:37:00,2018-11-02
329086,2400,22,vm-100,net.packetsTx.summation,\N,14.0,2018-11-02 03:37:00,2018-11-02
329087,2400,22,vm-100,virtualDisk.read.average,\N,0.0,2018-11-02 03:37:00,2018-11-02
329088,2400,22,vm-100,virtualDisk.write.average,\N,5.0,2018-11-02 03:37:00,2018-11-02
329089,2400,22,vm-100,net.usage.average,\N,0.0,2018-11-02 03:37:00,2018-11-02
329090,2400,22,vm-100,net.usage.average,vmnic5,0.0,2018-11-02 03:37:00,2018-11-02
329091,2400,22,vm-100,net.usage.average,vmnic2,0.0,2018-11-02 03:37:00,2018-11-02
329092,2400,22,vm-100,net.usage.average,vmnic1,0.0,2018-11-02 03:37:00,2018-11-02
329093,2400,22,vm-100,net.usage.average,vmnic0,0.0,2018-11-02 03:37:00,2018-11-02
329094,2400,22,vm-100,virtualDisk.numberReadAveraged.average,scsi0:1,0.0,2018-11-02 03:37:00,2018-11-02
329095,2400,22,vm-100,virtualDisk.numberReadAveraged.average,scsi0:0,0.0,2018-11-02 03:37:00,2018-11-02
329096,2400,22,vm-100,net.usage.average,vmnic4,0.0,2018-11-02 03:37:00,2018-11-02
329097,2400,22,vm-100,virtualDisk.numberWriteAveraged.average,scsi0:1,0.0,2018-11-02 03:37:00,2018-11-02
329098,2400,22,vm-100,virtualDisk.numberWriteAveraged.average,scsi0:0,0.0,2018-11-02 03:37:00,2018-11-02
329099,2400,22,vm-100,net.usage.average,4000,0.0,2018-11-02 03:37:00,2018-11-02
329100,2400,22,vm-100,net.usage.average,vmnic3,0.0,2018-11-02 03:37:00,2018-11-02